name: Deploy Testnet

on:
  push:
    branches:
      - testnet
  pull_request:
    types:
      - closed

concurrency:
  group: 'testnet'
  cancel-in-progress: true

jobs:
  testnet-live-deploy:
    if_merged:
      uses: ./.github/workflows/cloudflare-pages-deploy.yml
      with:
        environment: testnet
        near_wallet_env: testnet
      secrets: inherit
